import logo from "./../../components/logo.png"

const jobs = [
    {
        title: "Frontend Developer",
        company: "Tech Corp Innitiative",
        logo: logo,
        location: "Lagos, Nigeria",
        presence: "On-site, Hybrid",
        type: "Full-time",
        salary: "50000",
        salaryVal: "50,000/yr",
        description: "You will work on developing new features for our platform.",
    },
    {
        title: "Backend Engineer",
        company: "Innovatech Solutions Limited",
        logo: logo,
        location: "New York, United States",
        presence: "Remote",
        type: "Part-time",
        salary: "30000",
        salaryVal: "30,000/yr",
        description: "You will handle database management and server logic.",
    },
    {
        title: "Frontend Developer",
        company: "Tech Corp",
        logo: logo,
        location: "Lagos, Nigeria",
        presence: "On-site, Hybrid",
        type: "Full-time",
        salary: "50000",
        salaryVal: "50,000/yr",
        description: "You will work on developing new features for our platform.",
    },
    {
        title: "Backend Engineer",
        company: "Innovatech",
        logo: logo,
        location: "New York, United States",
        presence: "Remote",
        type: "Part-time",
        salary: "30000",
        salaryVal: "30,000/yr",
        description: "You will handle database management and server logic.",
    },
    {
        title: "Frontend Developer",
        company: "Tech Corp",
        logo: logo,
        location: "Lagos, Nigeria",
        presence: "On-site, Hybrid",
        type: "Full-time",
        salary: "50000",
        salaryVal: "50,000/yr",
        description: "You will work on developing new features for our platform.",
    },
    {
        title: "Backend Engineer",
        company: "Innovatech",
        logo: logo,
        location: "New York, United States",
        presence: "Remote",
        type: "Part-time",
        salary: "30000",
        salaryVal: "30,000/yr",
        description: "You will handle database management and server logic.",
    }
];

export default jobs;